[changelog]
header = "# Changelog\n\n"
body = """
{% if version %}## {{ version }}{% if date %} ({{ date }}){% endif %}\
{% else %}## Unreleased{% endif %}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}

{% for commit in commits -%}
- {{ commit.message | split(pat="\n") | first | trim }}
{% endfor %}
{% endfor %}
"""
footer = ""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
filter_commits = true
tag_pattern = "v[0-9]*"
sort_commits = "oldest"

[[git.commit_parsers]]
message = "^feat"
group = "Features"

[[git.commit_parsers]]
message = "^fix"
group = "Bug Fixes"

[[git.commit_parsers]]
message = "^perf"
group = "Performance"

[[git.commit_parsers]]
message = "^refactor"
group = "Refactoring"

[[git.commit_parsers]]
message = "^docs"
group = "Documentation"

[[git.commit_parsers]]
message = "^test"
group = "Tests"

[[git.commit_parsers]]
message = "^build"
group = "Build"

[[git.commit_parsers]]
message = "^ci"
group = "CI"

[[git.commit_parsers]]
message = "^chore"
group = "Chores"

[[git.commit_parsers]]
message = "^style"
group = "Refactoring"

[[git.commit_parsers]]
message = "^i18n"
group = "Documentation"
